### ISSUE TITLE
Creating GitHub actions

### ISSUE THREAD

**Issue by adulau** [D4-project/bgp-monitor#1]
- To run `black` on the code base
- Run the test at each commit

**Comment by enes-usta** [comment]
pre-commit sometimes corrupts my .git folder (miss configured ?)
I forgot to reinstall it
I will add pre-commit config files to dev branch

**Comment by enes-usta** [comment]
I found out what Github actions are last week, and so what you meant in this issue 😅 

Sorry for those notifications

**Comment by adulau** [comment]
Awesome! Thank you very much.
